2020-05-01 14:05:03,317	Exception occurred:
<class 'socket.gaierror'>: [Errno -2] Name or service not known
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 526, in resolve
    resolved = self.lookup_fn(address_str, port)

2020-05-01 14:05:03,339	Job number is not available yet
2020-05-01 14:05:03,341	Job number is not available yet
2020-05-01 14:05:03,373	File already exists: /var/loadtest/logs/2020-05-01_14-05-03.077290/phout_twtZ6l.log
2020-05-01 14:05:03,383	File already exists: /var/loadtest/logs/2020-05-01_14-05-03.077290/phantom_stat_vAq9Ql.log
2020-05-01 14:05:03,391	File not found to collect: validation_error.yaml
2020-05-01 14:05:03,403	File already exists: /var/loadtest/logs/2020-05-01_14-05-03.077290/answ_wGwYR_.log
2020-05-01 14:05:03,411	File already exists: /var/loadtest/logs/2020-05-01_14-05-03.077290/phantom_doC812.log
2020-05-01 14:10:44,690	Exception occurred:
<class 'socket.gaierror'>: [Errno -2] Name or service not known
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 526, in resolve
    resolved = self.lookup_fn(address_str, port)

2020-05-01 14:10:44,706	Job number is not available yet
2020-05-01 14:10:44,708	Job number is not available yet
2020-05-01 14:10:44,724	File already exists: /var/loadtest/logs/2020-05-01_14-10-44.517754/phout_l0k_DD.log
2020-05-01 14:10:44,729	File already exists: /var/loadtest/logs/2020-05-01_14-10-44.517754/phantom_dX3br7.log
2020-05-01 14:10:44,738	File already exists: /var/loadtest/logs/2020-05-01_14-10-44.517754/phantom_stat_zwpDjw.log
2020-05-01 14:10:44,743	File not found to collect: validation_error.yaml
2020-05-01 14:10:44,750	File already exists: /var/loadtest/logs/2020-05-01_14-10-44.517754/answ_62_rFr.log
2020-05-01 14:16:54,733	Job number is not available yet
2020-05-01 14:16:54,736	Job number is not available yet
2020-05-01 14:16:54,755	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/answ_djb09x.log
2020-05-01 14:16:54,760	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/phantom_L4xpLn.conf
2020-05-01 14:16:54,766	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/phantom_stdout_stderr_RpePLp.log
2020-05-01 14:16:54,781	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/phout__RRStV.log
2020-05-01 14:16:54,788	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/phantom_ZGjJh8.log
2020-05-01 14:16:54,795	File already exists: /var/loadtest/logs/2020-05-01_14-13-49.522176/phantom_stat_0fnTjL.log
2020-05-01 14:16:54,802	File not found to collect: validation_error.yaml
